config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, :controllers => { :omniauth_callbacks => "callbacks"  }
  root to: 'posts#index'
  
  resources :posts do
    member do
      put "like", to: "posts#upvote"
      put "dislike", to: "posts#downvote"
    end
    resources :comments do
      member do
        put "like", to: "comments#upvote"
        put "dislike", to: "comments#downvote"
      end
    end
  end

end

app/models/comment.rb
class Comment < ActiveRecord::Base
    acts_as_votable
	belongs_to :user
	belongs_to :post
	validates :message, presence: true
	validates :user,
		presence: true
	validates :post,
		presence: true
end

app/models/post.rb
class Post < ActiveRecord::Base
	acts_as_votable
	belongs_to :user
	has_attached_file :photo, styles: { medium: "600x400>", thumb: "150x100>" }, default_url: "/images/:style/missing.png"
  	validates_attachment_content_type :photo, content_type: /\Aimage\/.*\Z/
  	validates :photo, attachment_presence: true
	validates_with AttachmentSizeValidator, attributes: :photo, less_than: 5.megabytes
	has_many :comments, dependent: :destroy
	validates :title,
		uniqueness: true,
		presence: true
	validates :body,
		length: {minimum: 100, maximum:5000}
	validates :user,
		presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :posts, dependent: :destroy
  has_many :comments, through: :posts
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, :omniauth_providers => [:facebook,:google_oauth2]

	def self.from_omniauth(auth)
		where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
			user.provider = auth.provider
			user.uid = auth.uid
			user.email = auth.info.email
			user.password = Devise.friendly_token[0,20]
		end
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/callbacks_controller.rb
class CallbacksController < Devise::OmniauthCallbacksController
	def facebook
		logger.debug "Facebook Authentication"
		@user = User.from_omniauth(request.env["omniauth.auth"])
		sign_in_and_redirect @user
	end

	def google_oauth2
		logger.debug "Google Authentication"
		@user = User.from_omniauth(request.env["omniauth.auth"])
		sign_in_and_redirect @user
	end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_post, only: [:create]
  before_action :set_comment, only: [:destroy, :upvote, :downvote]
  before_action :authenticate_user!

  #Garantindo que somente o dono de um Post ou do Comentário pode pode executar a ação destroy
  before_filter :require_permission, only: [:destroy]

  def create
    #Construção de um comentário dentro do post.
    @comment = @post.comments.build(comment_params)
    #associando o usuário ao comentário
    @comment.user_id = current_user.id
    @comment.save
    redirect_to @post
  end
  def destroy
    #Encontrando um comentário dentro do post.
    @comment = @post.comments.find(params[:id])
    @comment.destroy
    redirect_to @post
  end

  def upvote
    @comment.upvote_by current_user
    redirect_to :back
  end

  def downvote
    @comment.downvote_by current_user
    redirect_to :back
  end

  private
    def require_permission
      set_comment
      if (current_user != @post.user) and (current_user != @comment.user)
        flash[:notice] = 'Permissões insuficientes!'
        redirect_to @post
      end
    end
    #precisamos encontrar o post para manipular o comentário dentro dele
    def set_post
      @post = Post.find(params[:post_id])
    end

    #precisamos encontrar o post para manipular o comentário dentro dele
    def set_comment
      set_post
      @comment = @post.comments.find(params[:id])
    end

    #agora não precisamos mais do post_id. Ele é preenchido automaticamente.
    def comment_params
      params.require(:comment).permit(:message)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy, :upvote, :downvote]
  before_action :authenticate_user!, except: [:show, :index, :upvote, :downvote]

  #Garantindo que somente o dono de um Post pode executar as ações de edit, update e destroy
  before_filter :require_permission, only: [:edit, :update, :destroy]

  def upvote
    @post.upvote_by current_user
    redirect_to :back
  end

  def downvote
    @post.downvote_from current_user
    redirect_to :back
  end

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    #Cria post já associado ao usuário
    @post = current_user.posts.build
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    #Cria post já associado ao usuário
    @post = current_user.posts.build(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to posts_path, notice: 'Post criado com sucesso.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post atualizado com sucesso.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post apagado com sucesso.' }
      format.json { head :no_content }
    end
  end

  private
    def require_permission
      if current_user != Post.find(params[:id]).user
        flash[:notice] = 'Permissões insuficientes!'
        redirect_to root_path
      end
    end
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :body, :photo)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def avatar_url(user)
      gravatar_id = Digest::MD5.hexdigest(user.email.downcase)
      "http://gravatar.com/avatar/#{gravatar_id}.png?s=48&d=mm"
    end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_comment.html.erb
<%= div_for(comment) do %>
  <div class="comments_wrapper clearfix">
    <div class="pull-left">
      <p class="lead">
        <%= comment.message %>
      </p>
      <p><small>Enviado há<strong> <%= time_ago_in_words(comment.created_at) %></strong> atrás por <strong>
        <% if comment.user == current_user %>
          você
        <% else %>
          <%= comment.user.email %>
        <%end%></strong>
      </small></p>
    </div>

    <% if user_signed_in? %>
  		<div class="btn-group pull-right">
  		  <%= link_to like_post_comment_path(comment.post, comment), method: :put, class: "btn btn-sm btn-default" do %>
  		    <span class="glyphicon glyphicon-thumbs-up"></span>
  		      Like
  		    <%= comment.get_upvotes.size %>
  		  <% end %>
  		  <%= link_to dislike_post_comment_path(comment.post, comment), method: :put, class: "btn btn-sm btn-default " do %>
  		    <span class="glyphicon glyphicon-thumbs-down"></span>
  		      Dislike
  		    <%= comment.get_downvotes.size %>
  		  <% end %>
  		  <%if (current_user == comment.post.user) or (current_user == comment.user)%>
  			  <%= link_to "Apagar comentário", [comment.post, comment], 
              method: :delete, 
    				  class: "btn btn-sm btn-default",
    					data: { confirm: "Tem certeza?" } %>
    		<% end %>
  		</div>
		<% end %>
  </div>
<% end %>

app/views/comments/_form.html.erb
<% if user_signed_in? %>
  <%= form_for([@post, @post.comments.build]) do |f| %>
    <div class="field">
      <%= f.text_area :message, class: "form-control" %>
    </div>
    <br>
    <div class="btn-group" role="group" aria-label="...">
      <%= button_tag(type: "submit", class: "btn btn-default btn-primary", name: "commit", value: "conceal") do %>
        Enviar comentário
      <% end %> 
    </div>
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Rails Blog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <header class="navbar navbar-default" role="navigation">
    <div class="navbar-inner">
      <div class="container ">
        <div id="logo" class="navbar-brand"><%= link_to "Rails Blog", root_path %></div>
        <nav class="collapse navbar-collapse navbar-ex1-collapse">
        <% if user_signed_in? %>
          <ul class="nav navbar-nav navbar-right">
            <li><%= link_to 'Novo Post', new_post_path %></li>
            <li><%= link_to 'Editar Conta', edit_user_registration_path %></li>
            <% if current_user.admin? %>
					    <li><%= link_to "Admin Panel", rails_admin_path %></li>
				  	<% end %>
            <li><%= link_to 'Sign out', destroy_user_session_path, :method => :delete %></li>
            <li class="round-image-50"><%= image_tag(avatar_url(current_user))%></li>
          </ul>
        <% else %>
          <ul class="nav navbar-nav pull-right">
            <li><%= link_to 'Sign up', new_user_registration_path %></li>
            <li><%= link_to 'Sign in', new_user_session_path %></li>
          </ul>
        <% end %>
        </nav>
      </div>
    </div>
  </header>

  <div id="main_content" class="container">
    <% flash.each do |name, msg| %>
      <%= content_tag(:div, msg, class: "alert alert-info") %>
    <% end %>

      <div id="content" class="col-md-9 center-block">
        <%= yield %>
      </div>
    </div>
  </div>
</body>
</html>

app/views/posts/_form.html.erb
<%= form_for(@post, html: { multipart: true }) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "erro") %> impediram a gravação desse post:</h2>

      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label "Título" %><br>
    <%= f.text_field :title, class: "form-control" %>
  </div>
  <div class="field">
    <%= f.label "Foto" %><br>
    <%= f.file_field :photo, class: "form-control" %>
  </div>
  <div class="field">
    <%= f.label "Corpo" %><br>
    <%= f.text_area :body, class: "form-control" %>
  </div>
  <br>
  <div class="btn-group" role="group" aria-label="...">
    <%= button_tag(type: "submit", class: "btn btn-default btn-primary", name: "commit", value: "conceal") do %>
      Salvar
    <% end %> 
    <% if @post.persisted? %>
      <%= link_to 'Ver Post', @post, class: 'btn btn-default btn-xs' %>
    <% end %>
    <%= link_to 'Voltar', posts_path, class: 'btn btn-default btn-xs' %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>
<%= render 'form' %>

app/views/posts/index.html.erb
<% @posts.each do |post| %>
<div class="link row clearfix">
  <div class="col-md-10">
    <div class="col-md-3">
      <br>
      <%= image_tag post.photo.url(:thumb) %>
    </div> 
    <div class="col-md-7">
      <h2>
        <%= link_to post.title, post %><br>
        <small class="author">Enviado há <%= time_ago_in_words(post.updated_at) %> atrás por <strong>
          <% if post.user == current_user %>
              você
          <% else %>
            <%= post.user.email %>
          <%end%></strong>
          </small>
      </h2>
    </div>
  </div>
  <% if user_signed_in? %>
    <div class="col-md-2 btn-group-vertical pull-right" role="group" aria-label="...">
      <%= link_to like_post_path(post), method: :put, class: "btn btn-default btn-xs" do %>
        <span class="glyphicon glyphicon-thumbs-up"></span>
          Like
        <%= post.get_upvotes.size %>
      <% end %>
      <%= link_to dislike_post_path(post), method: :put, class: "btn btn-default btn-xs" do %>
        <span class="glyphicon glyphicon-thumbs-down"></span>
          Dislike
        <%= post.get_downvotes.size %>
      <% end %>
      <%if current_user == post.user%>
        <%= link_to 'Editar Post', edit_post_path(post), class: 'btn btn-default btn-xs' %>
        <%= link_to 'Apagar Post'.html_safe, post, method: :delete, data: { confirm: 'Tem certeza?' }, class: 'btn btn-default btn-xs' %>
      <% end %>
    </div>
  <% end %>
</div>

<% end %>

app/views/posts/new.html.erb
<h1>Nova Publicação</h1>
<%= render 'form' %>

app/views/posts/show.html.erb
<div class="page-header">
  <h1>
	  <%= @post.title%><br>
	  <small class="author">Enviado há <%= time_ago_in_words(@post.updated_at) %> atrás por <strong>
      <% if @post.user == current_user %>
          você
      <% else %>
        <%= @post.user.email %>
      <%end%></strong>
    </small>
  </h1>
	<div class="lead">
    <%= image_tag @post.photo.url(:medium) %> <br><br>
		<%= simple_format(@post.body) %>
		<div class="btn-group" role="group" aria-label="...">
      <% if user_signed_in? %>
        <%= link_to like_post_path(@post), method: :put, class: "btn btn-default btn-xs" do %>
          <span class="glyphicon glyphicon-thumbs-up"></span>
            Like
          <%= @post.get_upvotes.size %>
        <% end %>
        <%= link_to dislike_post_path(@post), method: :put, class: "btn btn-default btn-xs" do %>
          <span class="glyphicon glyphicon-thumbs-down"></span>
            Dislike
          <%= @post.get_downvotes.size %>
        <% end %>
        <%if current_user == @post.user%>
    			<%= link_to 'Editar Post', edit_post_path(@post), class: 'btn btn-default btn-xs' %>
    			<%= link_to 'Deletar Post', @post, method: :delete, data: { confirm: 'Tem certeza?' }, class: 'btn btn-default btn-xs' %>
        <% end %>
      <% end %>
			<%= link_to 'Voltar', posts_path, class: 'btn btn-default btn-xs' %>
		</div>
	</div>
  
</div>

<% c=@post.comments.count %>
<h3 class="comments_title">
  <%if c > 0 %>
      <%= c %> 
      <% if c > 1 %>
        comentários
      <% else %>
        comentário
      <% end %>
  <%else%>
      sem comentários
  <%end%>
</h3>
<div id="comments">
  <%= render @post.comments %>
  <%= render "comments/form" %>
</div>